
'use server';

import { Resend } from 'resend';
import { redirect } from 'next/navigation';

const resend = new Resend(process.env.RESEND_API_KEY);

export async function submitOrder(formData: FormData) {
  const name = formData.get('name') as string;
  const phone = formData.get('phone') as string;
  const whatsapp = formData.get('whatsapp') as string;
  const address = formData.get('address') as string;
  const pkg = formData.get('package') as string;
  const upsell = formData.get('upsell') === 'on' ? 'Yes' : 'No';

  const packageNames: Record<string, string> = {
    pkg1: '1 Pack + 1 Free (₦27,000)',
    pkg2: '2 Packs + 2 Free (₦44,000) - BEST SELLER',
    pkg3: '10 Packs Bulk (₦105,000)',
  };

  try {
    // Note: To use a custom 'from' domain (e.g. sales@ageless.com), 
    // you must verify your domain in the Resend dashboard first.
    await resend.emails.send({
      from: 'Ageless Beauty Sales <onboarding@resend.dev>',
      to: 'cckelles@gmail.com',
      subject: `New Order: ${name} - ${packageNames[pkg] || pkg}`,
      html: `
        <div style="font-family: sans-serif; max-width: 600px; margin: auto; border: 1px solid #e2e8f0; border-radius: 20px; padding: 32px; color: #1a1a1a; background-color: #ffffff;">
          <h1 style="color: #6366f1; margin-bottom: 24px; font-size: 24px;">New Customer Order!</h1>
          <p style="font-size: 16px; color: #475569;">Great news! You have received a new order from the website.</p>
          
          <div style="background-color: #f8fafc; padding: 24px; border-radius: 16px; margin: 24px 0;">
            <p style="margin: 12px 0;"><strong>Customer Name:</strong> ${name}</p>
            <p style="margin: 12px 0;"><strong>Phone Number:</strong> ${phone}</p>
            <p style="margin: 12px 0;"><strong>WhatsApp:</strong> ${whatsapp || 'N/A'}</p>
            <p style="margin: 12px 0;"><strong>Selected Package:</strong> ${packageNames[pkg] || pkg}</p>
            <p style="margin: 12px 0;"><strong>Upsell (Botox Solution):</strong> ${upsell}</p>
            <p style="margin: 12px 0;"><strong>Delivery Address:</strong><br/>${address}</p>
          </div>
          
          <p style="font-size: 12px; color: #94a3b8; margin-top: 32px; text-align: center; border-top: 1px solid #e2e8f0; pt-24px;">
            This email was automatically generated by the Ageless Beauty Order System.
          </p>
        </div>
      `,
    });
  } catch (error) {
    console.error('Failed to send email:', error);
    return { error: 'Failed to process order. Please try again.' };
  }

  redirect('/thank-you');
}
